version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7.18
    steps:
      - checkout
      - run: echo "Hello there. First circleci pipeline."
      - run: sleep 25

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
